# Generated by Django 4.2.11 on 2024-07-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('review_Count', models.IntegerField(default=0)),
            ],
        ),
    ]
